# **Chap 3**

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[0] = 1.0
points[0] = 5.0
points[0] = 3.0
points[0] = 2.0
points[0] = 1.0

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

In [17]:
some_list = list(range(6))
print(some_list[:])
print(some_list[1:4])
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1])
print(some_list[1:4:2])

[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


In [18]:
print(points[1:])
print(points[1:, :])
print(points[1:, 0])
print(points[None])

tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [19]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [20]:
batch_t = torch.randn(2, 3, 5, 5)

In [21]:
img_gray_native = img_t.mean(-3)
batch_gray_native = batch_t.mean(-3)
img_gray_native.shape, batch_gray_native.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [22]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [23]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [24]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

<ipython-input-24-847ddfeff394>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1900.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [25]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'colums')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'colums')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'colums')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'colums')


In [26]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'colums'))

In [27]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'colums'))

In [28]:
# gray_named = (img_named[...,:3] * weights_named).sum('channels')

차원의 이름이 달라서 오류 발생

In [29]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [30]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [31]:
short_points.dtype

torch.int16

In [32]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [33]:
double_points = torch.zeros(10, 2).to(dtype=torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [34]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [35]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [36]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## 7절

In [37]:
# (3, 2) 텐서이지만 실제로는 크기가 6인 배열
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-37-5a614dec01c2>:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [38]:
# 텐서를 거치지 않고 저장 공간으로 직접 접근 가능
points_storage = points.storage()
points_storage[0]

4.0

In [39]:
points.storage()[1]

1.0

In [40]:
# 차원에 무관하게 실제 저장 공간 레이아웃은 1차원
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [41]:
# _로 끝나는 연산 결과는 기존 텐서의 내용 변경
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 8절

In [42]:
# 저장 공간을 인데스로 접근하기 위해 사이즈, 오프셋, 스트라이드 정보에 의존
# 오프셋은 저장 공간에서 첫 포인트와의 위치 차이
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [43]:
# 사이즈는 차원 크기
second_point.size()

torch.Size([2])

In [44]:
second_point.shape

torch.Size([2])

In [45]:
# 스트라이드는 각 차원에서 인덱스를 하나 증가했을 때 저장 공간 상에서 몇 개 요소를 건너뛰어야 하는지에 대한 값
points.stride()

(2, 1)

In [46]:
# 2차원 텐서에서 요소 i, j에 접근한다면 저장 공간 상으로는 storage_offset + stride[0] * i + stride[1] * j 번째 요소
# 텐서를 통해 스토리지를 간접 접근하는 식으로 텐서의 Transpose(전치)나 일부만으로 더 작은 텐서 만드는 데 필요한 연산을 메모리 재할당을 하지 않으므로 저렴하게 수행 가능

In [47]:
# 특정 부분만 정의하여 서브텐서 제작 및 오프셋, 사이즈, 스트라이드 값 확인
second_point = points[1]
second_point.size()

torch.Size([2])

In [48]:
second_point.storage_offset()

2

In [49]:
second_point.stride()

(1,)

In [50]:
# points텐서보다 작은 차원을 가지지만 동일한 저장 공간을 가르키므로 second_point텐서를 변경하면 points텐서도 변경됨
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [51]:
# 이런 동작 방식이 항상 옳지는 않으므로 서브텐서를 새 텐서로 복제
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [52]:
# 2차원 텐서들에 대해 transpose를 사용하거나 t 함수 사용하여 전치
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [53]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [54]:
# points와 points_t는 같은 공간을 가르킴
print(id(points.storage()) == id(points_t.storage())) # python id함수의 변경으로 인해 False 출력되는 것으로 추정
print(points.storage())
print(points_t.storage())

False
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


In [55]:
# points와 points_t는 차원 정보와 스트라이드만 다르므로 다음과 같이 출력됨
print(points.stride(), points_t.stride())

(2, 1) (1, 2)


In [56]:
# 텐서에서 각 요소는 행 단위로 나뉘어짐. Ex)points[0, 0]에서 points[1, 0] 이동은 요소 두 개 이동하는 것이고 points[0, 0]에서 points[0, 1] 이동은 요소 한 개 이동

In [57]:
# 다차원 배열에서도 차원 정보와 스트라이드 바뀔 두 차원 지정하면 전치됨
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
print(some_t.shape, transpose_t.shape)
print(some_t.stride(), transpose_t.stride())

torch.Size([3, 4, 5]) torch.Size([5, 4, 3])
(20, 5, 1) (1, 5, 20)


In [58]:
# 가장 오른쪽 차원에서 시작해서 증가되는 형태로 저장소에 값이 펼쳐진 텐서는 contiguous로 정의
# 인접한(contiguous) 텐서는 값 순회 시 띄엄띄엄 참조하지 않아 데이터 지역성 관점에서 CPU 메모리 접근 효율이 좋음
# 실제 효율 여부는 사용하는 알고리즘에 따라 다를 수 있음

In [59]:
# 파이토치 텐서 연산 중 인접한 텐서에만 동작하는 경우가 있음 ex) view
# 이 경우 경고성 예외를 던져 명시적으로 contiguous를 호출하라고 알려줌
# 텐서가 이미 인접한 상태라면 contiguous가 실제로 하는 일은 없고 성능에도 영향 없음
points.is_contiguous()

True

In [60]:
points_t.is_contiguous()

False

In [61]:
# contiguous 메소드를 이용하여 인접하지 않은 텐서를 인접하게 만들 수 있음
# 텐서 내용은 동일하나 값의 배치와 스트라이드가 바뀐 텐서가 만들어짐
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [62]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [63]:
points_t.stride()

(1, 2)

In [64]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [65]:
points_t_cont.stride()

(3, 1)

In [66]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [67]:
# 항목을 열 단위로 배치하기 위해 새 저장 공간을 재편성 한 것에 주목
# 새 배치에 따라 스트라이드도 변화

## 9절

In [68]:
# 지금까지 본 텐서 저장 공간은 CPU 메모리에 대한 것
# 파이토치의 텐서는 GPU를 위한 메모리 공간에도 저장 가능
# 모든 텐서는 여러 GPU 중 특정 GPU 메모리 영역으로 이동할 수 있고 이렇게 대량 병렬 처리 연산을 빠르게 가능

In [69]:
# 텐서는 device 인자로 위치 지정 가능
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device = 'cuda')

In [70]:
# to 메소드 활용 가능
points_gpu = points.to(device='cuda')

In [72]:
# 이런 텐서가 위치하는 곳은 GPU의 RAM
# 보통 텐서 위치에 관계없이 동일한 사용자 API를 제공하므로 연산이 일어나는 장소에 상관없이 코드 작성이 쉬워짐
# GPU 둘 이상이면 0부터 시작하는 정수로 지명
points_gpu = points.to(device='cuda:0') # 이제부터 텐서 연산은 GPU에서 수행
points = 2 * points # CPU에서 실행
points_gpu = 2 * points.to(device='cuda') # GPU에서 실행

In [73]:
# 계산 후 points_gpu 텐서는 CPU 영역으로 이동하지 않음
# 위 코드는 아래와 같은 단계 실행
# points 텐서를 GPU에 복사 -> GPU에서 새 텐서 할당 후 곱셈 결과 저장 -> GPU 텐서 핸들을 반환

In [74]:
points_gpu = points_gpu + 4 # 연산을 GPU에서 수행하며 출력하거나 결과 텐서 값에 접근하지 않으면 CPU에는 아무 정보도 전달되지 않음

In [76]:
# 텐서 CPU로 옮기려면 to 메소드에 cpu 인자 전달
points_cpu = points_gpu.to(device='cpu')

In [82]:
# to 메소드 대신 cpu나 cuda라는 축약 메소드 사용 가능
points_gpu = points.cuda() # default = 0
print(points_gpu.device)
points_gpu = points.cuda(0)
print(points_gpu.device)
points_cpu = points_gpu.cpu()
print(points_cpu.device)

cuda:0
cuda:0
cpu


In [ ]:
# to 메소드 사용시 device와 dtype 인자 동시 사용 가능

## 10절 - 넘파이 호환

In [83]:
# points 텐서를 넘파이 배열로 바꾸는 법
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [84]:
# 텐서의 저장 공간을 그대로 버퍼로 사용하여 데이터가 CPU RAM 영역에 있는 한 numpy 메소드를 추가 비용 없이 실행 가능
# 넘파이 배열 수정 시 원래 텐서에도 적용
# 텐서가 GPU에 할당되어 있다면 파이토치가 CPU 영역으로 텐서 내용 복사하여 배열 생성

In [85]:
# 넘파이 배열을 파이토치 텐서로 변환
points = torch.from_numpy(points_np)

In [86]:
# 동일하게 버퍼 공유 전략으로 동일 공간에 위치한 텐서 얻을 수 있음
# 파이토치는 기본 숫자 타입이 32비트 부동소수점, 넘파이는 64비트이므로 변환 후 텐서 dtype 확인할 필요가 있음

## 11절 - 일반화된 텐서도 텐서다

In [88]:
# 실제 내부 구현과 텐서 API는 분리되어 있어 API 명세를 만족하면 실제 구현 상세는 몰라도 텐서로 간주할 수 있음
# 파이토치는 텐서 위치에 상관없이 알맞는 연산 함수 호출함 -> 분배(dispatching) 메커니즘
# 해당 텐서 타입에 맞는 백엔드 함수 사용하여 실행시킴
# 분배기는 확장 가능하도록 설계되었음

In [89]:
# 양자화된 텐서 존재
# 백엔드 연산을 특별하게 수행하도록 구현
# 텐서를 dense 혹은 strided라는 메모리 배치 방식으로 구별하기도 함

In [ ]:
# 파이토치가 다양한 하드웨어와 앱을 지원하며 텐서의 종류도 다양해짐
# 파이토치로 자료 표현과 연산 수행에 다양한 시도를 하며 새로운 종류는 늘어날 전망

## 12절 - 텐서 직렬화

In [90]:
# 텐서를 직접 만들 때 중요 데이터를 파일에 보관했다가 나중에 읽어들여 프로그램 실행마다 모델 재훈련하는 상황 예방
# 텐서 객체를 직렬화 하기 위해 내부적으로 pickle 사용하며 저장 공간을 위한 전용 직렬화 코드 가지고 있음

In [91]:
# points 텐서를 ourpoints.t 파일에 저장하는 코드
torch.save(points, '../ourpoints.t')

In [92]:
# 파일 이름 대신 파일 디스크립터 넣는 방식
with open('../ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [93]:
# 텐서로 불러들일 때는 한 줄
points = torch.load('../ourpoints.t')

In [94]:
# 다른 방식
with open('../ourpoints.t', 'rb') as f:
    points = torch.load(f)

In [95]:
# 파일 포맷이 호환되지 않아 파이토치 외의 소프트웨어로는 읽기 불가능

In [96]:
# 다른 라이브러리에 의존하는 시스템에서 파이토치 도합하는 경우 호환성 중요
# HDF5 포맷을 위한 라이브러리 필요
# ㄴ이식성이 높고, 광범위하게 지원되는, 중첩된 키-값 딕셔너리에서 직렬화된 정형 다차원 배열 표현하는 포맷
# 파이썬의 h5py 라이브러리로 HDF5 포맷에게 넘파이 배열 형태로 전달하거나 반환받을 수 있음

In [98]:
pip install h5py # h5py 설치 (책에는 다르게 나와 있는데 안되길래 그냥 pip 사용해봄)

In [99]:
# points텐서 넘파이로 변환해 create_dataset 함수에 전달하여 저장
import h5py

f = h5py.File('../ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [100]:
# 'coords'가 HDF5 파일의 키에 해당, 키와 키를 중첩 가능
# HDF5 포맷은 데이터가 디스크에 있는 상태에서 원하는 요소만 인덱스로 직접 접근할 수 있게 지원
# 데이터셋의 가장 뒤 포인트 2개 읽기
f = h5py.File('../ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [101]:
# 파일이 열리거나 데이터 셋 필요할 때 아직 실제 데이터는 읽지 않은 상태
# 요소를 읽기 전까지는 아직 디스크에 존재
# h5py는 위 코드에서 맨끝 요소 두 개에 접근해 넘파이 배열 API와 동일하게 동작하는 유사 넘파이 배열 객체 넘겨줌
# 이것을 torch.from_numpy 함수에 넘기면 바로 텐서를 얻을 수 있음 - 이 때는 데이터가 텐서의 저장 공간으로 복사된 상태
last_points = torch.from_numpy(dset[-2:])
f.close()

In [102]:
# HDF5 파일 닫으면 데이터 셋 무효화되므로 이후에는 dset 접근 시 예외 발생

## 연습 문제

In [108]:
a = torch.tensor(list(range(9))) # 사이즈([9]), 오프셋 0, 스트라이드(1,)
print(a, a.size(), a.storage_offset(), a.stride())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([9]) 0 (1,)


In [112]:
b = a.view(3, 3)
print(b)
print(id(a) == id(b))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
False


In [113]:
c = b[1:, 1:] # 사이즈([2, 2]), 오프셋 4, 스트라이드(3, 1)
print(c, c.size(), c.storage_offset(), c.stride())

tensor([[4, 5],
        [7, 8]]) torch.Size([2, 2]) 4 (3, 1)


In [125]:
cosin = torch.cos(a)
sqrt = torch.sqrt(a)
print(cosin, sqrt)
print(torch.cos(a[1]), torch.sqrt(a[8])) # 돼는데 왜 오류가 발생한다고 할까

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455]) tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])
tensor(0.5403) tensor(2.8284)
